baseurl = "http://example.org/"
languageCode = "en-us"
title = "Adam Darnell"
theme = "hyde"



[params]
  themeColor = "theme-base-ad"
  description = "Pastor of South Durham Church, Durham, NC, USA."

[[menu.main]]
    URL = "http://sermons.southdurham.org"
    Name = "Sermons"
    weight = 20
