baseurl = "https://adamdarnell.netlify.com/"
languageCode = "en-us"
title = "Adam Darnell"
theme = "hyde"
googleAnalytics = "UA-106765449-1"

[params]
  themeColor = "theme-base-ad"
  description = "Pastor of South Durham Church in Durham, North Carolina."

[[menu.main]]
    URL = "http://sermons.southdurham.org"
    Name = "Sermons"
    weight = 20

[[menu.main]]
    URL = "http://www.southdurham.org"
    Name = "South Durham Church"
    weight = 30
